name: CI/CD for Testing

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  test-container-job:
    runs-on: ubuntu-latest
    container: node:22

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 1
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Connect to PostgreSQL with TypeORM
        run: node dist/index.js

        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          # POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          # POSTGRES_DB: ${{secrets.POSTGRES_DB}}

      # - name: Verify PostgreSQL connection
      #   run: |
      #     pg_isready -h localhost -p 5432 -U ${{ secrets.POSTGRES_USER }}

      - run: npm run build --if-present
      - run: npm test
